
spring:
  application:
    name: SBSA-Assessment1
  output:
    ansi:
      enabled: detect
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;INIT=CREATE SCHEMA IF NOT EXISTS PUBLIC
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    web: DEBUG
    org.springframework.web: INFO
    za.co.standardbank.assessment1: DEBUG
  file:
    path: logs
    name: ${logging.file.path}/assessment1.log

app:
#  pathToUserCsvFile: classpath:data/Users.csv
  pathToUserCsvFile: C:\Users\fsopmboudjieka\Documents\Study\Users2.csv
